
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FDMSAPP
{

using System;
    using System.Collections.Generic;
    
public partial class list_history
{

    public long ListHistoryID { get; set; }

    public int ListAnimeID { get; set; }

    public int ListAccountID { get; set; }

    public System.DateTime created_at { get; set; }

}

}
