//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMSAPP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class animeEntities : DbContext
    {
        public animeEntities()
            : base("name=animeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> accounts { get; set; }
        public virtual DbSet<anime> animes { get; set; }
        public virtual DbSet<genre> genres { get; set; }
        public virtual DbSet<list> lists { get; set; }
        public virtual DbSet<list_history> list_history { get; set; }
        public virtual DbSet<review> reviews { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<season> seasons { get; set; }
        public virtual DbSet<studio> studios { get; set; }
        public virtual DbSet<anime_studio> anime_studio { get; set; }
        public virtual DbSet<genre_anime> genre_anime { get; set; }
    }
}
