
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FDMSAPP
{

using System;
    using System.Collections.Generic;
    
public partial class review
{

    public long ReviewID { get; set; }

    public int AnimeID { get; set; }

    public int AccountID { get; set; }

    public int score { get; set; }

    public string content { get; set; }

    public System.DateTime created_at { get; set; }

    public Nullable<System.DateTime> deleted_at { get; set; }

}

}
